# 数据库的连接新
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall-wms
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 312210331Hwt
  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: 124.222.167.36:8848 #配置注册中心
  application:
    name: ware #配置注册中心,需要定义服务名称

#classpath* * 表示不仅扫描当前依赖而且扫描相关依赖
mybatis-plus:
  mapper-location: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto #主键自增
server:
  port: 8050
