server:
  port: 8040

# 数据库的连接新
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall-pms
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 312210331Hwt
  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: 124.222.167.36:8848
    alicloud:
      access-key: LTAI5tFZV5RXJ1Q4nLfCT4bY
      secret-key: eDzKXVkERFpCSTStdhZOUqXkyKfJv5
      oss:
        endpoint: https://oss-cn-hangzhou.aliyuncs.com
  application:
    name: product
#    设置全局服务器返回的日期格式
  jackson:
    date-format: yyyy-MM-dd HH-mm-ss
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  redis:
    host: 124.222.167.36
    port: 6379
#  cache:
#    type: redis
#classpath* * 表示不仅扫描当前依赖而且扫描相关依赖
mybatis-plus:
  mapper-location: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto #主键自增


