spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall-oms
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 312210331Hwt
  cloud:
    nacos:
      discovery:
        server-addr: 124.222.167.36:8848
#      config:
#        group: dev
  application:
    name: order


#classpath* * 表示不仅扫描当前依赖而且扫描相关依赖
mybatis-plus:
  mapper-location: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto #主键自增
server:
  port: 8030

user:
  username: hwt
  age: 12

