spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 124.222.167.36:8848
    gateway:
      routes:
        - id: route1-renren
          uri: lb://renren-fast
          predicates:
            - Path=/captcha.jpg,/sys/**
          filters:
            - PrefixPath=/renren-fast
        - id: route2-product
          uri: lb://product
          predicates:
            - Path=/product/**
          filters:
            - RewritePath=/product/(?<segment>/?.*),/product/$\{segment}
        - id: route2-mall.com
          uri: lb://product
          predicates:
            - Host=mall.com,item.com
        - id: route3-thirdParty
          uri: lb://thirdParty
          predicates:
            - Path=/third/**
          filters:
            - RewritePath=/third/(?<segment>/?.*),/thirdParty/$\{segment}
        - id: route4-member
          uri: lb://member
          predicates:
            - Path=/member/**
          filters:
            - RewritePath=/member/(?<segment>/?.*),/member/$\{segment}
        - id: route5-ware
          uri: lb://ware
          predicates:
            - Path=/ware/**
          filters:
            - RewritePath=/ware/(?<segment>/?.*),/ware/$\{segment}
        - id: route6-search.com
          uri: lb://search
          predicates:
            - Host=search.com
        - id: route7-auth.com
          uri: lb://authServer
          predicates:
            - Host=auth.com

server:
  port: 8070
